# Generated by Django 3.1.1 on 2020-11-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201110_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='makeup',
            name='dupes',
            field=models.ManyToManyField(to='main_app.Dupe'),
        ),
    ]
